"""Data contracts shared by generation, validation, BigQuery and Looker Studio."""

from __future__ import annotations

TABLE_CONTRACTS: dict[str, tuple[str, ...]] = {
    "dim_date": (
        "date",
        "year",
        "quarter",
        "month",
        "month_name",
        "iso_week",
        "day_of_week",
        "day_name",
        "is_weekend",
    ),
    "dim_users": (
        "user_id",
        "signup_date",
        "acquisition_channel",
        "platform",
        "country",
        "subscription_tier",
    ),
    "dim_matches": (
        "match_id",
        "match_date",
        "kick_off",
        "competition_id",
        "competition_name",
        "season_id",
        "season_name",
        "home_team_id",
        "home_team_name",
        "away_team_id",
        "away_team_name",
        "home_score",
        "away_score",
    ),
    "dim_teams": ("team_id", "team_name"),
    "dim_players": ("player_id", "player_name", "team_id", "team_name"),
    "dim_content": (
        "content_id",
        "match_id",
        "content_type",
        "published_at",
        "team_id",
        "player_id",
    ),
    "fact_match_events": (
        "event_id",
        "match_id",
        "event_index",
        "event_ts",
        "period",
        "minute",
        "second",
        "event_type",
        "team_id",
        "player_id",
        "possession_team_id",
        "x",
        "y",
        "end_x",
        "end_y",
        "shot_xg",
        "shot_outcome",
        "pass_outcome",
        "duel_type",
        "under_pressure",
        "duration_seconds",
    ),
    "fact_app_events": (
        "event_id",
        "user_id",
        "session_id",
        "event_ts",
        "event_date",
        "event_name",
        "match_id",
        "content_id",
        "platform",
        "acquisition_channel",
        "experiment_variant",
        "campaign_id",
        "revenue_usd",
    ),
    "fact_campaign_spend": (
        "spend_date",
        "campaign_id",
        "channel",
        "impressions",
        "clicks",
        "installs",
        "spend_usd",
        "target_spend_usd",
    ),
    "fact_experiment_assignments": (
        "user_id",
        "experiment_name",
        "variant",
        "assigned_at",
    ),
}

PRIMARY_KEYS: dict[str, tuple[str, ...]] = {
    "dim_date": ("date",),
    "dim_users": ("user_id",),
    "dim_matches": ("match_id",),
    "dim_teams": ("team_id",),
    "dim_players": ("player_id",),
    "dim_content": ("content_id",),
    "fact_match_events": ("event_id",),
    "fact_app_events": ("event_id",),
    "fact_campaign_spend": ("spend_date", "campaign_id"),
    "fact_experiment_assignments": ("user_id", "experiment_name"),
}

BIGQUERY_LAYOUT: dict[str, dict[str, object]] = {
    "dim_date": {"partition": "date"},
    "dim_users": {},
    "dim_matches": {"partition": "match_date", "clusters": ["competition_id"]},
    "dim_teams": {},
    "dim_players": {"clusters": ["team_id"]},
    "dim_content": {"clusters": ["match_id", "content_type"]},
    "fact_match_events": {
        "partition": "event_ts",
        "partition_type": "DAY",
        "clusters": ["match_id", "event_type"],
    },
    "fact_app_events": {
        "partition": "event_date",
        "clusters": ["user_id", "match_id", "event_name"],
    },
    "fact_campaign_spend": {"partition": "spend_date", "clusters": ["channel"]},
    "fact_experiment_assignments": {"clusters": ["experiment_name", "variant"]},
}
